---
title: "FORECASTING THE 2019 CANADIAN FEDERAL ELECTION IF EVERYONE HAD VOTED"
author: "Jiayi YANG"
date: "2020/12/10"
output: pdf_document
fontsize: 12pt
sansfont: Calibri Light
abstract: |
  In this paper, we aim to forecast the result 2019 Canadian Federal election if 
  everyone participated in the vote.In order to achieve the goal, we firstly 
  develop a logistic regression model using the data given by Canadian Election 
  Survey(CES). To improve the precision on prediciton, we then use Multilevel 
  regression with postratification (MRP) using the observations from Stat Canada 
  2016 Education Census. The result suggests that some social-demographic 
  variables have large impacts on individual choicses in the Canadian Federal 
  Election.
  
  **Keywords:** Public Opinion; 2019 Canadian Federal Election; Bayesian Approach; Multilevel Regression with Poststratification
---

# 1 Introduction
The 2019 Canadian Federal Election was hold on October 21, 2019. It was in order to elect members of the House of Commons to the 43rd Canadian Parliament. As a result, the leader of the Liberal Party, Justin Trudeau, won 184 seats finally and continued to be the Prime Minister of Canada. Although Justin Trudeau received 39.4% of the last election, it is worth noting that in the previous national Popular vote he only received less than 35%. The Liberals have the lowest national support among all the parties. So, we wondered if all the Canadian citizens with age over 18 could vote in the last election, how would the results of the election change. In this study, we attempt to determine the possibility that Justin Trudeau would still be elected when the eligible voters were expanded to be all the Canadian citizens who meet the requirements.

To accomplish this goal, we do analysis based on the data from Canadian Election Survey (CES) and Stat Canada 2016 Education Census. We will firstly build a logistic regression by Bayesian approach. And then, we will also utilize the multilevel regression model with post-stratification. We analyzed individual-level survey data and post-stratified census data to analyze the effects caused by key demographic variables on the voting decision and predict the probability of Justin Trudeau still winning the election. Our prediction suggests that, as the voter has been expanded to all the citizen, the probability that Trudeau will still be elected is x%.

In section two, we present the datasets we analysis. It includes the source and the summary of these two datasets, we also interpret the meaning of them. In section three, we show the models we built, and use AIC method choose the best prediction model out of them. Followed by this, in section four, we describe and conclude the result we find by the model. Finally, in section five, we give a conclusion of our study and do discussion on the weakness of our study and consider what else can we do to improve this study. 


\pagebreak

# 2 Data

## 2.1 Display CES data

aaa

## 2.2 Display Stat Canada 2016 Eduaction Census dataset

bbb

## 2.3 Methodology

ccc

\pagebreak

# 3 Model Development
## 3.1 Logistic regression model using Bayesian approach
ddd

## 3.2 Multilevel regression with post-stratification (MRP)

eeee

\pagebreak

# 4 Results
ffff

\pagebreak

# 5 Discussion
## 5.1 Conclusion
gg
## 5.2 Weakness
hhhh
## 5.3 Next step
iiii


\pagebreak

# Appendix

All code used to generate this results can be found here: 

https//..a

# References